<?php

namespace Daw\DietaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministradorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Daw\DietaBundle\Controller\AdministradorController();
        return $instance;
    }
}
