Daw\DietaBundle\Entity\Articulo:
    type: entity
    table: articulo
    indexes:
        titulo:
            columns:
                - titulo
    uniqueConstraints:
        img:
            columns:
                - img
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        descripcion:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        tipo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        fuente:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        fechapub:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
        img:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks:
        prePersist: [setFechapub]
