Daw\DietaBundle\Entity\Dia:
    type: entity
    table: dia
    uniqueConstraints:
        calendario:
            columns:
                - calendario
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: false
            comment: ''
        horario:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
    manyToOne:
        calendario:
            targetEntity: Calendario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                calendario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
